name: w_notes
description: Flutter Note App
publish_to: 'none' 
version: 1.0.4+30
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^3.26.0
  google_fonts: ^2.1.0
  sqflite: ^2.0.0+3
  flutter_staggered_grid_view: ^0.3.4
  intl:

dev_dependencies:
  cider:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"
  sqflite_common_ffi: ^2.1.0

flutter_launcher_name:
  name: "w notes"



flutter:
  uses-material-design: true
  