default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build appbundle --release")

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "beta",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
    )
  end
  

  desc "Deploy nova versão para Google Play Store"
  lane :deploy do
    
    # sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build appbundle --release")
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end
end
