# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  

  desc "Deploy nova versão para Google Play Store"
  lane :deploy do

    sh("set -e")

    # Find and increment the version number.
    sh("perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' ../../pubspec.yaml")
      
    # Commit and tag this change.
    sh("version=`grep 'version: ' ../../pubspec.yaml | sed 's/version: //'`")
    sh("git commit -m  'docs: Bump version to $version' ../../pubspec.yaml")
    sh("git tag $version")
    
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build appbundle --release")
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end
end
